Makefile: Do not dump the environment during db-prepare
The resources.yaml file does not exists at the beginning of the db-prepare calls
but the environment wants to read it which leads to the following error:

Preparing artix7 files
============================
Traceback (most recent call last):
  File ".../prjxray/utils/create_environment.py", line 62, in <module>
    main()
  File ".../prjxray/utils/create_environment.py", line 55, in main
    environment = get_environment_variables()
  File ".../prjxray/utils/create_environment.py", line 37, in get_environment_variables
    part_info = get_part_information(db_root, part)
  File ".../prjxray/prjxray/util.py", line 44, in get_part_information
    "Mapping file {} does not exists".format(filename)
AssertionError: Mapping file .../prjxray/database/artix7/mapping/parts.yaml does not exists

Do not dump the environment during this stage because the XRAY_PART is the only
neccessary information which is set in the <family>.sh script.

Signed-off-by: Daniel Schultz <d.schultz@phytec.de>
Signed-off-by: Steve <steve.bohan.liu@outlook.com>